### ISSUE TITLE
Latest master is not working on iOS 12 & 13

### ISSUE THREAD

**Issue by nilrog** [custom-cards/bignumber-card#10]
FYI this commit breaks this card on iOS devices running iOS 12 & 13 (HA is 0.109.6).
https://github.com/custom-cards/bignumber-card/commit/a5df3dab124a2c630f9d213fec54886ae93ce4b1

My guess is that something causes the card to not initialize properly on those devices because the end result is the same as if you forget to include it in the lovelace resources. The same change works fine in Firefox 76 on Windows. Reverting back to the commit before this one restores the card functionality on iOS.

**Comment by Molnigt** [comment]
I just got the same issue and simply removed the two top rows, the field definitions.

**_DEFAULT_STYLE = 'var(--label-badge-blue)';
_DEFAULT_COLOR = 'var(--primary-text-color)';**

I believe the must be set in the constructor to work in Safari and Edge. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields
