### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jzumerle** [custom-cards/bignumber-card#35]
Add support for entity icon, for example: 

showIcon: true / false 
or
positionIcon: left / right / top / bottom / none

Thanks!

**Comment by igorsantos07** [comment]
@jzumerle was this ever really done?

**Comment by ChrisWeiss** [comment]
I would also like to see this feature. I am using bignumber-card to display the state of my HVAC fan "Running/Stopped" and it would be nice to just use mdi-fan next to it rather than the `title:` text.
