### ISSUE TITLE
Background defaults to transparent?

### ISSUE THREAD

**Issue by mrand** [custom-cards/bignumber-card#4]
I have a relatively basic setup and recently changed themes.  In doing so, now my date and time card looks funny because it appears the bignumber-card defaults to a transparent background while all the other cards do not:

![Capture](https://user-images.githubusercontent.com/435987/64142749-f9d7b380-cdd2-11e9-9865-7d353799e3a6.PNG)

I suspect this is related to what this user is seeing as well: https://community.home-assistant.io/t/lovelace-bignumber-card/59280/28

Thanks!

**Comment by iantrich** [comment]
you can use card-mod to apply the desired background
