### ISSUE TITLE
Option to remove unit of measurement?

### ISSUE THREAD

**Issue by haakonstorm** [custom-cards/bignumber-card#5]
Great plugin!
Would love to be able to natively remove the unit of measurement, e.g. ´%´ and ´hours´-- see screenshot:

<img width="313" alt="Screenshot of Safari (22-10-2019, 15-54-31)" src="https://user-images.githubusercontent.com/193781/67293099-3e82ef80-f4e4-11e9-8bca-92a31c090878.png">

**Comment by iantrich** [comment]
create a template sensor with no unit of measure

**Comment by hajo62** [comment]
A template sensor doubles the number of sensors monitored.
I would also like to have that option.
